### PR TITLE
Added and override methods/views that generate files during export with external ids

### PR DESCRIPTION
**Pull request by kurkop**
Updated:
- module_prototyper/models/module_prototyper.py: 
  - Added set_keep_external_ids method: Set the the keep_external_ids from the wizard keep_external_ids will help to update all external ids or keep exsting ones.
  - Added topological_sort method: Items must be provided in the form of an iterable, where the key has a tuple.
  - Modify generate_data_files method: Added code to contruct a better data file.
  - Added order_data method: Create a hierarchy to export external ids, using a level dependent of parent.
  - Added generate_external_id method: Create all external ids to later export.
  - Added fixup_data method: Order, generate external ids and load all data to export.
  - Added deps_detect method: Detect depedencies on the data fields.
  - Add fields_ignore to some methods: This variable transport a information related by "Circular dependency cleaning" from wizard 'volatile" to export methods.
- module_prototyper/wizard/module_prototyper_module_export.py:
  - Added fields (keep_external_ids, fields_selected, fields_selected_initial, fields_not_selected): Keep_external_ids guaranted that the external_ids in the database are not rewrite when export module. fields_selected\* is used to store the cleanup data when exists a circular dependency.
  - dep_solve, action export, zip_files override: This override guaranted the correct "circular dependency cleaning" in exporting methods (see fields_ignore).
- module_prototyper/wizard/module_prototyper_module_export_view.xml: 
  - Added fields_selected, fields_selected_initial, fields_not_selected to the export wizard.
- module_prototyper/templates/8.0/data/model_name.xml.template: 
  - Added logic to generate fields with all addtional information.

@blaggacao Please explain better

### CODE REVIEW

**Comment by blaggacao** [comment]
This PR improves greatly the functionality and usability of data export by implementing toposort algorithms for files, records. @pedrobaeza @max3903 Can you please support us to get this merge-ready soon?

Features (among others):
- **Toposort for files and records**
- Circular dependency resolve wizard
- Fields ordering (alphabetically)
- Chose to keep existing external ids to better fit your data generation workflow.
- Clean-up magic columns
- Refactored jinja template to be exportable (or almost) out of the box

**Comment by blaggacao** [comment]
@kurkop tavis-ci failed.

```
======== Testing test_flake8 ========
./module_prototyper/wizard/module_prototyper_module_export.py:155:45: E126 continuation line over-indented for hanging indent
./module_prototyper/models/module_prototyper.py:227:80: E501 line too long (84 > 79 characters)
./module_prototyper/models/module_prototyper.py:763:45: E126 continuation line over-indented for hanging indent
./module_prototyper/models/module_prototyper.py:765:45: E126 continuation line over-indented for hanging indent
```

**Comment by blaggacao** [comment]
Closes #2

**Comment by kurkop** [comment]
The travis checks are OK.

@blaggacao @pedrobaeza @max3903

**Comment by blaggacao** [comment]
:+1: let's get this into the upstream asap...

**Comment by blaggacao** [comment]
Thanks, very cool! Any bug reports, just tag me or @kurkop :smile:

**Comment by max3903** [comment]
@kurkop Thanks for your contribution. No need to merge against our branch, you can directly make your PR against the OCA branch next time.

https://github.com/OCA/server-tools/pull/276

**Pull request merged**
